//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MovieReviewDataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class Language
    {
        public int Language_ID { get; set; }
        public string Language_Name { get; set; }
        public Nullable<bool> Is_Active { get; set; }
    }
}
