//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MovieReviewDataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class MovieReview
    {
        public MovieReview()
        {
            this.MovieReviewScores = new HashSet<MovieReviewScore>();
        }
    
        public int MovieReview_ID { get; set; }
        public string Movie_Name { get; set; }
        public Nullable<int> Language_ID { get; set; }
        public Nullable<System.DateTime> Release_Date { get; set; }
        public string Starcast { get; set; }
        public string Music { get; set; }
        public string Banner { get; set; }
        public string Review_Text { get; set; }
        public Nullable<int> Star_Rating { get; set; }
        public string Trailer_Link { get; set; }
        public Nullable<int> MovieReview_StatusType_ID { get; set; }
        public Nullable<int> Person_ID { get; set; }
        public string Modified_User { get; set; }
        public Nullable<System.DateTime> Modified_Date { get; set; }
        public Nullable<int> ThumbsUpCount { get; set; }
        public Nullable<int> ThumbsDownCount { get; set; }
        public string ImageOne { get; set; }
        public string ImageTwo { get; set; }
        public string ImageThree { get; set; }
        public string ImageFour { get; set; }
        public string ImageFive { get; set; }
        public string Generation { get; set; }
    
        public virtual Language Language { get; set; }
        public virtual MovieReview_StatusType MovieReview_StatusType { get; set; }
        public virtual ICollection<MovieReviewScore> MovieReviewScores { get; set; }
        public virtual Person Person { get; set; }
    }
}
