//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MovieReviewDataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class MovieReview_StatusType
    {
        public int MovieReview_StatusType_ID { get; set; }
        public string MovieReview_StatusType_Name { get; set; }
        public string Is_Active { get; set; }
        public string Description { get; set; }
    }
}
