//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MovieReviewDataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class MovieReviewScore
    {
        public int MovieReviewScoreID { get; set; }
        public int MovieReviewID { get; set; }
        public int PersonID { get; set; }
        public bool ThumbsUp { get; set; }
        public string DeviceID { get; set; }
    
        public virtual Person Person { get; set; }
    }
}
