//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MovieReviewDataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class Person
    {
        public string First_Name { get; set; }
        public string Middle_Name { get; set; }
        public string Last_Name { get; set; }
        public string User_ID { get; set; }
        public string Home_Phone { get; set; }
        public string Mobile_Phone { get; set; }
        public string Gender { get; set; }
        public Nullable<System.DateTime> DOB { get; set; }
        public Nullable<decimal> MaxInvalidAttempts { get; set; }
        public string Is_Locked { get; set; }
        public Nullable<int> Role_ID { get; set; }
        public string Modified_User { get; set; }
        public Nullable<System.DateTime> Modified_Date { get; set; }
        public string Country { get; set; }
        public string Password { get; set; }
        public int Person_ID { get; set; }
    
        public virtual Role Role { get; set; }
    }
}
